# Generated by Django 2.2.3 on 2019-12-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='happenedAt',
            new_name='happened_at',
        ),
    ]
