# Generated by Django 2.2.3 on 2019-12-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20191215_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visitedAt',
            new_name='visited_at',
        ),
    ]
