# Generated by Django 2.2.3 on 2019-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20191215_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
