# Generated by Django 2.2.9 on 2019-12-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191221_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.Doctor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nurse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.Nurse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.Patient'),
        ),
    ]
